language: rust

rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx

# Test on nightly Rust, but failures there won't break the build.
matrix:
  allow_failures:
    - rust: nightly

# Run the test for just the binary crate. as it will build  & test everything.
# TODO: make Travis run Invoke tasks instead
script: cargo test --no-fail-fast --manifest-path ./crates/rush/Cargo.toml
sudo: false
