language: rust

rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx

# Test on nightly Rust, but failures there won't break the build.
matrix:
  allow_failures:
    - rust: nightly

sudo: false
script:
  - cargo build
  - cargo test --no-fail-fast
