site_name: rush
site_description: "Succinct & readable processing language for the shell"
site_author: "Karol Kuczmarski"

theme: 'material'

docs_dir: 'docs'
site_dir: 'release/docs'

pages:
- API: 'api.md'

markdown_extensions:
- smarty
- toc:
    permalink: True
